//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RBG.Utility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RBG.Utility.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العميل غير موجود. هل تريد الاستمرار ؟ .. علماَ بأنة إذا قررت الاستمرار سيتم إضافة هذا العميل إلي قاعدة البيانات.
        /// </summary>
        internal static string ClientNotExists {
            get {
                return ResourceManager.GetString("ClientNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر.
        /// </summary>
        internal static string ComboBoxDefaultText {
            get {
                return ResourceManager.GetString("ComboBoxDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم السري الحالي غير صحيح.
        /// </summary>
        internal static string CurrentPasswordInvalid {
            get {
                return ResourceManager.GetString("CurrentPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم الحالي غير صحيح.
        /// </summary>
        internal static string CurrentUsernameInvalid {
            get {
                return ResourceManager.GetString("CurrentUsernameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إدخال الفاتورة بنجاح.
        /// </summary>
        internal static string InvoiceCreatedSuccessfully {
            get {
                return ResourceManager.GetString("InvoiceCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قم بإدخال المواد / الخامات أولاً.
        /// </summary>
        internal static string InvoiceWithoutItems {
            get {
                return ResourceManager.GetString("InvoiceWithoutItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك تأكد من اسم العميل.
        /// </summary>
        internal static string MakeSureOfClientName {
            get {
                return ResourceManager.GetString("MakeSureOfClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكمية المتاحة {0}.
        /// </summary>
        internal static string MaterialAvailableQuantity {
            get {
                return ResourceManager.GetString("MaterialAvailableQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكود الذي أدخلتة مستخدم من قبل. هل تريد الاستمرار ؟.
        /// </summary>
        internal static string MaterialCodeAlreadyUsed {
            get {
                return ResourceManager.GetString("MaterialCodeAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكود والاسم مستخدمان من قبل. هل تريد الاستمرار ؟.
        /// </summary>
        internal static string MaterialCodeAndNameAlreadyUsed {
            get {
                return ResourceManager.GetString("MaterialCodeAndNameAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الذي أدخلتة مستخدم من قبل. هل تريد الاستمرار ؟.
        /// </summary>
        internal static string MaterialNameAlreadyUsed {
            get {
                return ResourceManager.GetString("MaterialNameAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إضافة الكمية بنجاح.
        /// </summary>
        internal static string MaterialQuantityAddedSeccessfully {
            get {
                return ResourceManager.GetString("MaterialQuantityAddedSeccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الجديدة وتأكيدها يجب أن تكونا متطابقتان.
        /// </summary>
        internal static string NewPasswordConfirmationNotMached {
            get {
                return ResourceManager.GetString("NewPasswordConfirmationNotMached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم إدخال أي خامات بالفاتورة.
        /// </summary>
        internal static string NoItemsAdded {
            get {
                return ResourceManager.GetString("NoItemsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار المادة / الخامة.
        /// </summary>
        internal static string ShouldSelectMaterial {
            get {
                return ResourceManager.GetString("ShouldSelectMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ملئ هذا الحقل.
        /// </summary>
        internal static string ThisFieldIsRequired {
            get {
                return ResourceManager.GetString("ThisFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل بيانات المستخدم بنجاح.
        /// </summary>
        internal static string UpdateAdminDataSuccessfully {
            get {
                return ResourceManager.GetString("UpdateAdminDataSuccessfully", resourceCulture);
            }
        }
    }
}
