USE [RPG]
GO
ALTER TABLE Clients ADD Email NVARCHAR(MAX) NULL
GO
ALTER TABLE Clients ADD Facebook NVARCHAR(MAX) NULL
GO
ALTER TABLE Clients ADD Viber NVARCHAR(MAX) NULL
GO
ALTER TABLE Clients ADD WhatsApp NVARCHAR(MAX) NULL
GO
ALTER TABLE Clients ADD Other NVARCHAR(MAX) NULL
GO