//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseInvoice()
        {
            this.PurchaseInvoiceItems = new HashSet<PurchaseInvoiceItem>();
            this.PurchaseInvoicePayments = new HashSet<PurchaseInvoicePayment>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int SupplierId { get; set; }
        public decimal Total { get; set; }
        public decimal Paid { get; set; }
        public decimal Discount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseInvoiceItem> PurchaseInvoiceItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseInvoicePayment> PurchaseInvoicePayments { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
