USE [master]
GO

/****** Object:  Database [RBG]    Script Date: 3/6/2018 11:55:18 PM ******/
CREATE DATABASE [RBG]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RBG', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\RBG.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RBG_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\RBG_log.ldf' , SIZE = 1280KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [RBG] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RBG].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RBG] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RBG] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RBG] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RBG] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RBG] SET ARITHABORT OFF 
GO

ALTER DATABASE [RBG] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RBG] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [RBG] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RBG] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RBG] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RBG] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RBG] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RBG] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RBG] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RBG] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RBG] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RBG] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RBG] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RBG] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RBG] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RBG] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RBG] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RBG] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RBG] SET RECOVERY FULL 
GO

ALTER DATABASE [RBG] SET  MULTI_USER 
GO

ALTER DATABASE [RBG] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RBG] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RBG] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RBG] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [RBG] SET  READ_WRITE 
GO


