USE[master]
GO
/****** Object:  Database [RPG]    Script Date: 18-Sep-20 9:37:05 AM ******/
CREATE DATABASE[RPG]
 CONTAINMENT = NONE
 ON  PRIMARY
(NAME = N'RPG', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\RPG.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON
(NAME = N'RPG_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\RPG_log.ldf' , SIZE = 1280KB , MAXSIZE = 2048GB , FILEGROWTH = 10 %)
GO
ALTER DATABASE[RPG] SET COMPATIBILITY_LEVEL = 110
GO
IF(1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC[RPG].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE[RPG] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE[RPG] SET ANSI_NULLS OFF
GO
ALTER DATABASE[RPG] SET ANSI_PADDING OFF
GO
ALTER DATABASE[RPG] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE[RPG] SET ARITHABORT OFF
GO
ALTER DATABASE[RPG] SET AUTO_CLOSE OFF
GO
ALTER DATABASE[RPG] SET AUTO_SHRINK OFF
GO
ALTER DATABASE[RPG] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE[RPG] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE[RPG] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE[RPG] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE[RPG] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE[RPG] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE[RPG] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE[RPG] SET DISABLE_BROKER
GO
ALTER DATABASE[RPG] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE[RPG] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE[RPG] SET TRUSTWORTHY OFF
GO
ALTER DATABASE[RPG] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE[RPG] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE[RPG] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE[RPG] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE[RPG] SET RECOVERY FULL
GO
ALTER DATABASE[RPG] SET  MULTI_USER
GO
ALTER DATABASE[RPG] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE[RPG] SET DB_CHAINING OFF
GO
ALTER DATABASE[RPG] SET FILESTREAM(NON_TRANSACTED_ACCESS = OFF)
GO
ALTER DATABASE[RPG] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO
ALTER DATABASE[RPG] SET DELAYED_DURABILITY = DISABLED
GO
EXEC sys.sp_db_vardecimal_storage_format N'RPG', N'ON'
GO
ALTER DATABASE[RPG] SET QUERY_STORE = OFF
GO
USE[RPG]
GO
/****** Object:  Table [dbo].[Admins]    Script Date: 18-Sep-20 9:37:06 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE[dbo].[Admins]
(

   [Id][int] IDENTITY(1,1) NOT NULL,

  [Username] [nvarchar] (500) NOT NULL,

   [Password] [nvarchar] (500) NOT NULL,
 CONSTRAINT[PK__Admins__3214EC0768AA4387] PRIMARY KEY CLUSTERED
(
   [Id] ASC
)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON[PRIMARY]
) ON[PRIMARY]
GO
/****** Object:  Table [dbo].[Clients]    Script Date: 18-Sep-20 9:37:06 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE[dbo].[Clients]
(

   [Id][int] IDENTITY(1,1) NOT NULL,

  [Name] [nvarchar] (500) NOT NULL,

   [Phone] [nvarchar] (50) NULL,
	[Address] [nvarchar] (500) NULL,
	[Email]
[nvarchar]
(max) NULL,
	[Facebook] [nvarchar]
(max) NULL,
	[Viber] [nvarchar]
(max) NULL,
	[WhatsApp] [nvarchar]
(max) NULL,
	[Other] [nvarchar]
(max) NULL,
 CONSTRAINT[PK__Clients__3214EC073C7FC429] PRIMARY KEY CLUSTERED
(
   [Id] ASC
)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON[PRIMARY]
) ON[PRIMARY] TEXTIMAGE_ON[PRIMARY]
GO
/****** Object:  Table [dbo].[InvoiceItems]    Script Date: 18-Sep-20 9:37:06 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE[dbo].[InvoiceItems]
(

   [Id][int] IDENTITY(1,1) NOT NULL,

  [InvoiceId] [int]
NOT NULL,

  [MaterialId] [int]
NOT NULL,

  [Quantity] [decimal] (18, 2) NOT NULL,

   [Price] [decimal] (18, 2) NOT NULL,
	[Notes] [nvarchar]
(max) NULL,
 CONSTRAINT[PK__InvoiceI__3214EC07E1C627A1] PRIMARY KEY CLUSTERED
(
   [Id] ASC
)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON[PRIMARY]
) ON[PRIMARY] TEXTIMAGE_ON[PRIMARY]
GO
/****** Object:  Table [dbo].[InvoicePayments]    Script Date: 18-Sep-20 9:37:06 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE[dbo].[InvoicePayments]
(

   [Id][int] IDENTITY(1,1) NOT NULL,

  [InvoiceId] [int]
NOT NULL,

  [Date] [datetime]
NOT NULL,

  [Paid] [decimal] (18, 2) NOT NULL,
CONSTRAINT[PK__InvoiceP__3214EC074D6D2541] PRIMARY KEY CLUSTERED
(
  [Id] ASC
)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON[PRIMARY]
) ON[PRIMARY]
GO
/****** Object:  Table [dbo].[Invoices]    Script Date: 18-Sep-20 9:37:06 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE[dbo].[Invoices]
(

   [Id][int] IDENTITY(1,1) NOT NULL,

  [Date] [datetime]
NOT NULL,

  [ClientId] [int]
NOT NULL,

  [Total] [decimal] (18, 2) NOT NULL,

   [Paid] [decimal] (18, 2) NOT NULL,
	[Discount] [decimal] (18, 2) NOT NULL,
  CONSTRAINT[PK_Invoices] PRIMARY KEY CLUSTERED
(
	[Id] ASC
)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON[PRIMARY]
) ON[PRIMARY]
GO
/****** Object:  Table [dbo].[Materials]    Script Date: 18-Sep-20 9:37:06 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE[dbo].[Materials]
(

   [Id][int] IDENTITY(1,1) NOT NULL,

  [Code] [nvarchar] (500) NOT NULL,

   [Name] [nvarchar] (500) NOT NULL,
	[Price] [decimal] (18, 2) NOT NULL,
 
	 [Quantity] [decimal] (18, 2) NOT NULL,
  
	  [IsArchived] [bit]
NOT NULL,
  
	  [IsDeleted] [bit]
NOT NULL,
   CONSTRAINT[PK_Materials] PRIMARY KEY CLUSTERED
 (
	 [Id] ASC
 )WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON[PRIMARY]
) ON[PRIMARY]
GO
SET IDENTITY_INSERT[dbo].[Admins]
ON
GO
INSERT[dbo].[Admins]
([Id], [Username], [Password]) VALUES(1, N'dev', N'E77989ED21758E78331B20E477FC5582')
GO
SET IDENTITY_INSERT[dbo].[Admins]
OFF
GO
ALTER TABLE[dbo].[Materials] ADD DEFAULT((0)) FOR[IsDeleted]
GO
ALTER TABLE[dbo].[InvoiceItems] WITH CHECK ADD CONSTRAINT[FK_InvoiceItems_Invoices] FOREIGN KEY([InvoiceId])
REFERENCES[dbo].[Invoices]
([Id])
GO
ALTER TABLE[dbo].[InvoiceItems]
CHECK CONSTRAINT[FK_InvoiceItems_Invoices]
GO
ALTER TABLE[dbo].[InvoiceItems] WITH CHECK ADD CONSTRAINT[FK_InvoiceItems_Materials] FOREIGN KEY([MaterialId])
REFERENCES[dbo].[Materials]
([Id])
GO
ALTER TABLE[dbo].[InvoiceItems]
CHECK CONSTRAINT[FK_InvoiceItems_Materials]
GO
ALTER TABLE[dbo].[InvoicePayments] WITH CHECK ADD CONSTRAINT[FK_InvoicePayments_Invoices] FOREIGN KEY([InvoiceId])
REFERENCES[dbo].[Invoices]
([Id])
GO
ALTER TABLE[dbo].[InvoicePayments]
CHECK CONSTRAINT[FK_InvoicePayments_Invoices]
GO
ALTER TABLE[dbo].[Invoices] WITH CHECK ADD CONSTRAINT[FK_Invoices_Clients] FOREIGN KEY([ClientId])
REFERENCES[dbo].[Clients]
([Id])
GO
ALTER TABLE[dbo].[Invoices]
CHECK CONSTRAINT[FK_Invoices_Clients]
GO
USE[master]
GO
ALTER DATABASE[RPG] SET  READ_WRITE
GO
